# OSCCAR variables and aliases, also sourcing OpenFOAM's variables.
#

# Set the OSCCAR install directory
export OSCCAR_DIR=$HOME/OSCCAR

# Specify a version of the code, if applicable
#export OSCCAR_PROJECT=FOO
# OSCCAR home with project name
#export OSCCAR_HOME=$OSCCAR_DIR/OSCCAR-$OSCCAR_PROJECT

# OSCCAR home without project name
export OSCCAR_HOME=$OSCCAR_DIR/OSCCAR

# Source OpenFOAM's variables
source $OSCCAR_DIR/OpenFOAM-2.3.x/etc/bashrc

export OSCCAR_APP=$OSCCAR_HOME/applications
export OSCCAR_SRC=$OSCCAR_HOME/src
export OSCCAR_TUTORIALS=$OSCCAR_HOME/tutorials
export OSCCAR_UTILITIES=$OSCCAR_HOME/utilities
export OSCCAR_SOLVERS=$OSCCAR_HOME/solvers
export OSCCAR_DOC=$OSCCAR_HOME/doc
export OSCCAR_RUN=$FOAM_RUN

source $OSCCAR_HOME/etc/aliases.sh
