/*---------------------------------------------------------------------------*\

Header
    myCode.H

Description
    myCode is a header to include some output message.

\*---------------------------------------------------------------------------*/

// This message lets people know how bad code duplication actually is.
Info<< "Code duplication is naughty." << endl;


// ************************************************************************* // 
