#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

wmakeCheckPwd "$OSCCAR_APP" || {
    echo "Error: Current directory is not \$OSCCAR_APP"
    echo "    The environment variables are inconsistent with the installation."
    echo "    Check the OSCCAR entries in your dot-files and source them."
    exit 1
}

[ -n "$FOAM_EXT_LIBBIN" ] || {
    echo "Error: FOAM_EXT_LIBBIN not set"
    echo "    Check the OSCCAR entries in your dot-files and source them."
    exit 1
}

set -x

wmake all utilities $*
wmake all solvers $*

# ----------------------------------------------------------------- end-of-file
