#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication topoSet
runApplication createPatch -overwrite

cp -r 0.org 0
runApplication setFields

runApplication $(getApplication)

runApplication sample

gnuplot plotVelocityProfile.gp

# ----------------------------------------------------------------- end-of-file
